


* 入门
本章概述了 Calc——GNU Emacs 计算器：它是什么，如何启动和退出，以及它的各种使用方式。

** Calc 是什么？
Calc 是一个高级计算器和数学工具，作为 GNU Emacs 环境的一部分运行。它大致基于 HP-28/48 系列计算器，并具有以下多种功能：
- 提供代数表示法或逆波兰表示法（RPN，即基于堆栈）的计算输入方式。
- 支持任意精度的整数和浮点数。
- 能够对有理数、复数（直角坐标和极坐标）、包含标准偏差的误差形式、开区间和闭区间、向量和矩阵、日期和时间、无穷大、集合、带有单位的量以及代数公式进行运算。
- 提供诸如对数和三角函数等数学运算。
- 提供编程功能（按位操作和非十进制数）。
- 提供未来价值和内部收益率等财务函数。
- 提供如素因数分解和任意模 m 算术等数论功能。
- 提供代数操作功能，包括符号微积分。
- 能够在常规编辑缓冲区之间移动数据。
- 支持嵌入模式，可以直接在任何编辑缓冲区中操作 Calc 公式和数据。
- 可以使用 GNUPLOT（一种多功能且免费的绘图程序）绘制图形。
- 提供易于使用的编程功能，可以使用键盘宏、代数公式、代数重写规则或扩展的 Emacs Lisp 编写程序。

Calc 力求为每个人提供一些有用的功能，因此它功能丰富，对于初次使用者来说可能会显得有些复杂。
如果你只计划将 Calc 用作传统的桌面计算器，那么你只需要阅读本手册的“入门”章节，可能还需要阅读教程的前几部分。
随着你对这个程序越来越熟悉，你可以逐步学习它的其他功能。
Calc 的范围和深度不及功能齐全的符号数学软件包，但 Calc 具有方便、可移植和自由的优点。

** 关于本手册
本文件为 GNU Emacs 计算器的完整描述，既可作为初学者的入门指南，也可作为有经验用户的参考。
尽管拥有一些 GNU Emacs 的使用经验有助于更好地使用 Calc，但即使你不熟悉或不经常使用 Emacs，这本手册也应该是可以阅读的。\\

本手册分为三个主要部分：你现在正在阅读的“入门”章节、Calc 教程，以及 Calc 参考手册。\\

如果你急于使用 Calc，下文有一个简短的“演示”，在几页内展示 Calc 的主要功能。
如果你没有时间完整阅读教程，这部分内容将展示你开始使用所需的所有信息。详见 Calc 演示。\\

教程章节通过大量的实际操作示例和解释，逐步引导你了解 Calc 的各个部分。
如果你是 Calc 的新手并且有些时间，可以至少尝试阅读教程的开头部分。
教程包括大约 70 个带有答案的练习题，这些练习不仅可以帮助你熟练使用 Calc，还能指出一些有趣而独特的使用方式。\\

参考部分对 Calc 进行了全面深入的讨论。如果你想了解 Calc 的每个方面，可以从头到尾阅读参考手册；
或者，你可以查找目录或概念索引，找到手册中讨论你需要了解的内容。\\

每个 Calc 键盘命令都在 Calc 概要和按键索引中列出。代数函数、M-x 命令和变量也都有自己的索引。\\

在 Calc 中，随时按下 h i 键序列可以在线访问本手册。在 Calc 窗口之外，你可以按 C-x * i 在线阅读手册。
在 Calc 中，命令 h t 将直接跳到教程；在 Calc 之外，命令 C-x * t 将跳转到教程并在必要时启动 Calc。
按下`h s 或 C-x * s 会直接转到 Calc 概要。
在 Calc 中，你还可以使用 h k、h f 或 h v 命令分别跳转到描述 Calc 键、函数或变量的手册部分。详见 帮助命令。\\

Calc 手册可以打印，但由于手册非常大，只有在确实需要时才建议打印副本。
要打印手册，你需要使用 TeX 排版程序（这是斯坦福大学 Donald Knuth 开发的一个免费程序），
以及 texindex 程序和 texinfo.tex 文件，这些都可以从 FSF 作为 texinfo 软件包的一部分获得。
要将 Calc 手册打印为一个大的册子，你需要 Emacs 的源代码，其中包含本手册的源代码 calc.texi。
切换到 Emacs 源代码分发的 doc/misc 子目录，其中包含本手册的源代码，然后输入 make calc.pdf。
（TeX 运行时出现一些“超限框”警告也不用担心。）最终将生成本手册的 pdf 文件。

























