#+title:  org快速指南
#+author: JanSky
#+date:   2024-07-27


* 简介
Org 是一种使用快速有效的纯文本系统记笔记、维护待办事项列表和进行项目规划的模式。
它也是一个创作和发布系统，支持使用源代码进行文字编程和可重复的研究。
本文档是 Org 手册的精简版。它包含所有基本功能和命令，以及自定义的重要提示。
它适用于那些因为篇幅过大而不愿阅读 200 页手册的初学者。

** 安装
重要提示：如果您使用的 Org 版本是 Emacs 发行版的一部分，请跳过此部分并直接转到激活。
将从网上下载的 org 模块添加到 Emacs 配置中以激活
#+begin_src emacs-lisp
  (add-to-list 'load-path "~/path/to/orgdir/lisp")
#+end_src

** 激活
将以下几行添加到您的 Emacs 初始化文件中，为三个命令定义全局键，这些键在任何 Emacs 缓冲区（而不仅仅是 Org 缓冲区）中都很有用。
可根据自身习惯自行选择合适的键。
#+begin_src emacs-lisp
  (global-set-key (kbd "C-c l") #'org-store-link)
  (global-set-key (kbd "C-c a") #'org-agenda)
  (global-set-key (kbd "C-c c") #'org-capture)
#+end_src

** 反馈
如果您发现 Org 存在问题，或者您有疑问、评论或想法，请发送邮件至 Org 邮件列表 mailto:emacs-orgmode@gnu.org。
有关如何提交错误报告的信息，请参阅主手册。


* 文档结构
Org 是一个大纲工具。大纲允许将文档组织成层次结构，对我来说，这是笔记和想法的最佳表示。
通过折叠可以概览此结构，即隐藏文档的大部分内容以仅显示一般文档结构和当前正在处理的部分。
Org 通过将整个显示和隐藏功能压缩为与 TAB 键 org-cycle 绑定的单个命令，大大简化了整体的使用。

** 标题
标题定义了大纲树的结构。Org 中的标题从左边距1开始，以一个或多个星号开头，后跟一个空格。例如：
#+begin_src org
  * 顶级标题
  ** 第二级
  *** 第三级
      一些文本
  *** 第三级
      更多文本
  * 另一个顶级标题
#+end_src
请注意，命名的标题 org-footnote-section 默认为 '脚注'，被视为特殊。具有此标题的子树将被导出函数默认忽略。
有些人觉得很多星星太嘈杂，他们更喜欢轮廓上有空白，后面跟着一颗星星作为标题开头。请参阅杂项，了解实现此目的的设置。

** 可见的循环
TAB 功能使得在缓冲区中隐藏文本的部分成为可能。
Org 模式使用两个命令，分别绑定到 TAB 和 S-TAB（org-cycle 和 org-shifttab），以改变缓冲区中的可见性。

+ TAB (org-cycle)
  子树循环：在当前子树的状态之间轮换。

+ S-TAB (org-global-cycle)
  C-u TAB (org-cycle)
  全局循环：在整个缓冲区的状态之间轮换

当 Emacs 首次访问 Org 文件时，全局状态设置为概览，即仅可见顶级标题。
可以通过变量 org-startup-folded 进行配置，或者通过在文件中添加 STARTUP 关键字来进行文件级别的配置。
关键字可以是 overview、content、showall、showeverything 或 show<n>levels（n = 2..5），例如：
#+begin_src org
  #+STARTUP: content
#+end_src

** 移动
以下命令用于跳转到缓冲区中的其他标题。

+ C-c C-n (org-next-visible-heading) \\
  跳转到下一个标题。
  
+ C-c C-p (org-previous-visible-heading) \\
  跳转到上一个标题。
  
+ C-c C-f (org-backward-heading-same-level) \\
  跳转到下一个同级标题。
  
+ C-c C-b (outline-backward-same-level) \\
  跳转到上一个同级标题。
  
+ C-c C-u (outline-up-heading) \\
  向上跳转到更高层级的标题。

** 结构编辑
+ M-RET (org-meta-return) \\
  插入与当前级别相同的新标题。如果光标在普通列表项中，则创建一个新项（参见普通列表）。
  当在行中间使用此命令时，当前行会被拆分，剩余部分成为新的标题。
  
+ M-S-RET (org-insert-todo-heading) \\
  在当前标题级别插入新的 TODO 项目。
  
+ TAB (org-cycle) \\
  在新的空条目中，TAB 循环切换合理的级别。
  
+ M-LEFT (org-metaleft) M-RIGHT (org-metaright) \\
  将当前标题提升或降低一级。
  
+ M-UP (org-move-subtree-up) M-DOWN (org-move-subtree-down) \\
  将子树上移或下移，即与同级的前一个或下一个子树交换位置。
  
+ C-c C-w (org-refile) \\
  将条目或区域重新归档到不同的位置。参见“重新归档和复制”。
  
+ C-x n s (org-narrow-to-subtree) C-x n w (widen) \\
  将缓冲区限制到当前子树，然后再扩大它。

当有一个活动区域（瞬态标记模式）时，提升和降级操作将作用于该区域内的所有标题。

** 稀疏树
Org mode 的一个重要功能是能够为大纲树中的选定信息构建稀疏树，使整个文档尽可能地折叠。
同时将选定的信息及其上方的标题结构显示出来。只需尝试一下，你就会立即明白它是如何工作的。

Org mode 包含几个创建这种树的命令，所有这些命令可以通过调度器访问：

+ C-c / (org-sparse-tree) \\
  这将提示你输入一个额外的键来选择一个创建稀疏树的命令。

+ C-c / r (org-occur) \\
  Occur。提示输入一个正则表达式，并显示一个包含所有匹配项的稀疏树。每个匹配项也会被高亮显示；按下 C-c C-c 可以取消高亮显示。

其他稀疏树命令根据 TODO 关键字、标签或属性来选择标题，这些将在本手册的后续部分讨论。

** 普通列表
在大纲树的条目中，手工格式化的列表可以提供额外的结构。它们还提供了一种创建复选框列表的方式（参见复选框）。
Org 支持编辑这些列表，并且每个导出器（参见导出）都可以解析和格式化它们。
Org 支持有序列表、无序列表和描述列表。
无序列表项以‘-’，‘+’，或‘*’作为项目符号开始。
有序列表项以‘1.’ 或 ‘1)’ 开始。
描述列表使用‘::’来分隔术语和描述。

属于同一列表的项目必须在第一行具有相同的缩进。一个项目在下一个与其项目符号/编号对齐的行或更少的缩进之前结束。
一个列表在所有项目都闭合后结束，或在两个空行之前结束。示例如下：
#+begin_src org
  * 《魔戒》
    我最喜欢的场景是（按以下顺序）
    1. Rohirrim 的攻击
    2. Eowyn 与巫王的战斗
       + 这已经是我在书中的最喜欢的场景
       + 我非常喜欢 Miranda Otto。
    这部电影中的重要演员有：
    - Elijah Wood :: 他饰演弗罗多
    - Sean Astin :: 他饰演山姆，弗罗多的朋友。
#+end_src
当光标位于项目的第一行（带有项目符号或编号的行）时，以下命令会对项目执行操作

+ TAB (org-cycle) \\
  项目可以像标题级别一样折叠。

+ M-RET (org-insert-heading) \\
  在当前级别插入新项目。使用前缀参数时，强制插入新标题（请参见结构编辑）。

+ M-S-RET (org-insert-todo-heading) \\
  插入一个带有复选框的新项目（请参见复选框）。

+ M-UP (org-move-item-up) M-DOWN (org-move-item-down) \\
  将当前项目（包括子项目）上移/下移（与相同缩进的前一个/下一个项目交换）。如果列表是有序的，自动重新编号。

+ M-LEFT (org-do-promote) M-RIGHT (org-do-demote) \\
  减少/增加项目的缩进，不影响子项目。

+ M-S-LEFT (org-promote-subtree) M-S-RIGHT (org-demote-subtree) \\
  减少/增加当前项目及其子项目的缩进。

+ C-c C-c (org-toggle-checkbox) \\
  如果项目行中有复选框（参见复选框），切换复选框的状态。同时验证整个列表中的项目符号和缩进一致性。

+ C-c - (org-cycle-list-bullet) \\
  在整个列表级别之间循环不同的项目符号（‘-’，‘+’，‘*’，‘1.’，‘1)’）。


* 表格







